/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 9667df890fc47c243ab4cc7d1a147fe5)
interface __BaseEnv_Env {
	EDGE_RATE_LIMITER: RateLimit;
	USER_RATE_LIMITER: RateLimit;
	DEVICE_RATE_LIMITER: RateLimit;
	CHAT_RATE_LIMITER: RateLimit;
	PAYMENT_RATE_LIMITER: RateLimit;
	ALLOWED_ORIGINS: "altgrid://app,http://127.0.0.1:3000,http://localhost:3000";
	LICENSE_KEY_ID: "altgrid-license-v1";
	SUPABASE_URL: string;
	SUPABASE_SERVICE_ROLE_KEY: string;
	MERCADOPAGO_ACCESS_TOKEN: string;
	MERCADOPAGO_WEBHOOK_SECRET: string;
	MERCADOPAGO_WEBHOOK_URL: string;
	PRIVATE_LICENSE_KEY: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ALLOWED_ORIGINS" | "LICENSE_KEY_ID" | "SUPABASE_URL" | "SUPABASE_SERVICE_ROLE_KEY" | "MERCADOPAGO_ACCESS_TOKEN" | "MERCADOPAGO_WEBHOOK_SECRET" | "MERCADOPAGO_WEBHOOK_URL" | "PRIVATE_LICENSE_KEY">> {}
}
