/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 01e806e77be2631a857ac3c445292896)
interface __BaseEnv_Env {
	EDGE_RATE_LIMITER: RateLimit;
	USER_RATE_LIMITER: RateLimit;
	DEVICE_RATE_LIMITER: RateLimit;
	CHAT_RATE_LIMITER: RateLimit;
	PAYMENT_RATE_LIMITER: RateLimit;
	ALLOWED_ORIGINS: "altgrid://app,https://localhost,http://localhost,capacitor://localhost,http://127.0.0.1:3000,http://localhost:3000,http://127.0.0.1:4173,https://acvisualdigital.github.io,https://altgrid.com.br,https://www.altgrid.com.br";
	LICENSE_KEY_ID: "altgrid-license-v1";
	WHATSAPP_GRAPH_API_VERSION: "v23.0";
	WHATSAPP_TEMPLATE_NAME: "altgrid_admin_alert";
	WHATSAPP_TEMPLATE_LANGUAGE: "pt_BR";
	SUPABASE_URL: string;
	SUPABASE_SERVICE_ROLE_KEY: string;
	PRIVATE_LICENSE_KEY: string;
	MERCADOPAGO_ACCESS_TOKEN: string;
	MERCADOPAGO_WEBHOOK_SECRET: string;
	MERCADOPAGO_WEBHOOK_URL: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ALLOWED_ORIGINS" | "LICENSE_KEY_ID" | "WHATSAPP_GRAPH_API_VERSION" | "WHATSAPP_TEMPLATE_NAME" | "WHATSAPP_TEMPLATE_LANGUAGE" | "SUPABASE_URL" | "SUPABASE_SERVICE_ROLE_KEY" | "PRIVATE_LICENSE_KEY" | "MERCADOPAGO_ACCESS_TOKEN" | "MERCADOPAGO_WEBHOOK_SECRET" | "MERCADOPAGO_WEBHOOK_URL">> {}
}
